[versions]
agp = "8.13.0"
gson = "2.13.2"
junitJupiterEngine = "6.0.0"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junit-jupiter = "5.8.1"
testng = "6.9.6"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesCore = "1.10.2"
kotlinxSerializationJsonJvm = "1.9.0"
lifecycleRuntimeKtx = "2.9.3"
activityCompose = "1.11.0"
composeBom = "2025.09.00"
materialIconsExtended = "1.7.8"
navigationCompose = "2.9.4"

adventure = "4.24.0"
log4j = "2.25.1"
netty = "4.2.0.Final"
expiringmap = "0.5.11"
network = "1.6.28-SNAPSHOT"
fastutil = "8.5.15"
lombok = "8.14.2"
checkerframework = "0.6.49"
math = "2.0"
nbt = "3.0.3.Final"
snappy = "2.0.2"
jose4j = "0.9.6"
minecraft-auth = "4.1.2"
jackson-databind = "2.20.0"
jackson-annotations = "2.20"
media3 = "1.5.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterEngine" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterEngine" }
testng = { group = "org.testng", name = "testng", version.ref = "testng" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-serialization-json-jvm = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "kotlinxSerializationJsonJvm" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

adventure-text-serializer-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-text-serializer-json = { group = "net.kyori", name = "adventure-text-serializer-json", version.ref = "adventure" }
log4j-bom = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core" }
netty-common = { group = "io.netty", name = "netty-common", version.ref = "netty" }
netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-codec = { group = "io.netty", name = "netty-codec", version.ref = "netty" }
netty-transport = { group = "io.netty", name = "netty-transport", version.ref = "netty" }
netty-transport-native-unix-common = { group = "io.netty", name = "netty-transport-native-unix-common", version.ref = "netty" }
expiringmap = { group = "net.jodah", name = "expiringmap", version.ref = "expiringmap" }
network-common = { group = "com.nukkitx.network", name = "common", version.ref = "network" }
fastutil-bom = { group = "org.cloudburstmc.fastutil", name = "bom", version.ref = "fastutil" }
fastutil-long-common = { group = "org.cloudburstmc.fastutil.commons", name = "long-common" }
fastutil-long-obj-maps = { group = "org.cloudburstmc.fastutil.maps", name = "long-object-maps" }
fastutil-int-obj-maps = { group = "org.cloudburstmc.fastutil.maps", name = "int-object-maps" }
fastutil-obj-int-maps = { group = "org.cloudburstmc.fastutil.maps", name = "object-int-maps" }
math = { group = "org.cloudburstmc.math", name = "immutable", version.ref = "math" }
nbt = { group = "org.cloudburstmc", name = "nbt", version.ref = "nbt" }
snappy = { group = "io.airlift", name = "aircompressor", version.ref = "snappy" }
jose4j = { group = "org.bitbucket.b_c", name = "jose4j", version.ref = "jose4j" }
minecraft-auth = { group = "net.raphimc", name = "MinecraftAuth", version.ref = "minecraft-auth" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-databind" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-annotations" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }

[bundles]
netty = [ "netty-common", "netty-buffer", "netty-codec", "netty-transport", "netty-transport-native-unix-common" ]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
checkerframework = { id = "org.checkerframework", version.ref = "checkerframework" }
